/// <reference path="../.astro/types.d.ts" />
/// <reference path="../worker-configuration.d.ts" />

type Runtime = import('@astrojs/cloudflare').Runtime<Env>;

// Augment Env with secrets not generated by wrangler types
interface Env {
  NVIDIA_API_KEY?: string;
  GOOGLE_AI_KEY?: string;
}

declare namespace App {
  interface Locals extends Runtime {}
}
